### ISSUE TITLE
setup.py still not working AFTER that merge commit

### ISSUE THREAD

**Issue by ArezalGame89** [Kiffolisk/pykern#4]
It still doesn't work because there's no module?
what else do i have to install? cause i tried everything
![image](https://user-images.githubusercontent.com/86628069/144837766-3cb77448-7791-4816-aec1-739379ef7a9f.png)

**Comment by Kiffolisk** [comment]
I don't remember what urllib required for install. My wifi is still not back and I'm using 4G right now. I'll try finding a fix later. Thanks for the issue

**Comment by Kiffolisk** [comment]
pip install urllib

**Comment by ArezalGame89** [comment]
> pip install urllib

![image](https://user-images.githubusercontent.com/86628069/144850736-f4f8e5fd-7141-415c-a73e-6f99a9499875.png)

this is always what i get

**Comment by Kiffolisk** [comment]
works on termux and my own pc. don't know.

**Comment by Kiffolisk** [comment]
> urllib is a standard library, you do not have to install it
Use Python3/reinstall it.
