### ISSUE TITLE
What if we could have community tools?

### ISSUE THREAD

**Issue by ArezalGame89** [Kiffolisk/pykern#8]
Wouldn't it be cool if we could download files from github that have the same purpose as the official pykern-sip. this would also make the project not dead!

# Alternative
If you could magically provide *much* more files like you did in downdb, then that also would not require communities nor anything else, just accepting the fact that you need to be more active on it :D

**Comment by ArezalGame89** [comment]
(shit i also realized people need to be careful and see thru what they downloading otherwise they're gonna get deeeaaaaad)

**Comment by Kiffolisk** [comment]
yeah that was my plan, people can make custom package managers and put them in the sip repo
